// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/components.tsx";
import * as $4 from "./routes/docs/[...slug].tsx";
import * as $5 from "./routes/gfm.css.ts";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/raw.ts";
import * as $8 from "./routes/showcase.tsx";
import * as $9 from "./routes/update.tsx";
import * as $$0 from "./islands/ComponentGallery.island.tsx";
import * as $$1 from "./islands/CopyArea.island.tsx";
import * as $$2 from "./islands/Counter.island.tsx";
import * as $$3 from "./islands/LemonDrop.island.tsx";
import * as $$4 from "./islands/SearchButton.island.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/components.tsx": $3,
    "./routes/docs/[...slug].tsx": $4,
    "./routes/gfm.css.ts": $5,
    "./routes/index.tsx": $6,
    "./routes/raw.ts": $7,
    "./routes/showcase.tsx": $8,
    "./routes/update.tsx": $9,
  },
  islands: {
    "./islands/ComponentGallery.island.tsx": $$0,
    "./islands/CopyArea.island.tsx": $$1,
    "./islands/Counter.island.tsx": $$2,
    "./islands/LemonDrop.island.tsx": $$3,
    "./islands/SearchButton.island.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
